version: "2"
services:
  web:
    image: bambou-apache2
    expose:
      - 80
    networks:
      - default
      - reverse-proxy
    restart: always
    environment:
      - VIRTUAL_HOST=bambou.nguyenantoine.com
      - LETSENCRYPT_HOST=bambou.nguyenantoine.com
      - LETSENCRYPT_EMAIL=antoine.ngu@outlook.fr
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
