version: "2"
services:
  web:
    image: bambou-web
    expose:
      - 80
    networks:
      - default
      - reverse-proxy
    restart: always
    env_file:
      - .env
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
